version: '3.8'

services:

  # ------------------ API ------------------
  api:
    build: ./car_testing_api
    container_name: car-classification-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://car_user:car_password@postgres:5432/car_classification
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - adv-net

  # ------------------ Frontend ------------------
  web:
    build: ./hosting
    container_name: car-classification-web
    ports:
      - "8080:8080"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - adv-net

  # ------------------ Postgres ------------------
  postgres:
    image: postgres:16
    container_name: car-classification-db
    environment:
      - POSTGRES_USER=car_user
      - POSTGRES_PASSWORD=car_password
      - POSTGRES_DB=car_classification
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - adv-net

  # ------------------ Certbot ------------------
  certbot:
    image: certbot/certbot
    container_name: car-classification-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "
      mkdir -p /var/www/certbot &&
      certbot certonly --webroot -w /var/www/certbot -d car.ams.cards --non-interactive --agree-tos -m your-email@example.com || true &&
      while :; do
        sleep 12h &
        wait $${!}
        certbot renew --webroot -w /var/www/certbot --quiet
      done
      "
    networks:
      - adv-net

  # ------------------ Nginx ------------------
  nginx:
    image: nginx:latest
    container_name: car-classification-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
      - web
      - certbot
    entrypoint: >
      sh -c "
        # wait for certs to exist
        until [ -f /etc/letsencrypt/live/car.ams.cards/fullchain.pem ]; do
          echo 'Waiting for SSL certificate...'; sleep 3;
        done
        nginx -g 'daemon off;'
      "
    restart: unless-stopped
    networks:
      - adv-net

networks:
  adv-net:
    driver: bridge