events {}
http {
    upstream web_app {
        server web:8080;
    }

    upstream api_app {
        server api:8000;
    }

    server {
        listen 80;
        server_name car.ams.cards;

        # frontend
        location / {
            proxy_pass http://web_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # backend api
        location /api/ {
            proxy_pass http://api_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}

